### PR TITLE
fix: make sure operation ids are unique #12

### LINKED ISSUE #12: Duplicate ids
Currently if you have 2 post methods:

- pets
- pets/1/owner

The ids will be the same.

### PR DESCRIPTION
**Pull request by patrickhoogkamer**
Currently it can happen that nested endpoints get the same operation id as their parent. This breaks swagger ui.

### CODE REVIEW

File: tests/GeneratorTest.php [hunk 1]
```diff
@@ -31,7 +34,33 @@ public function it_generates_open_api_spec_for_route()
...
+
+    protected function nestedRoutes($app)
+    {
+        /** @var Router $router */
+        $router = $app->make('router');
+        $router->middleware(['api'])->group(function (Router $router) {
+            $router->post('pets', [PetController::class, 'store']);
+
+            $router->post('pets/{pet}/owner', [PetController::class, 'storeOwner']);
+        });
```
Comment (tomasvanrijsse) [inline tests/GeneratorTest.php]: entity name is nu ook gefixt toch voor urls die lijken op `/resoure/{id}`?
Wil je daar een test voor hebben?

Comment (patrickhoogkamer) [reply tests/GeneratorTest.php]: I saw that index and show methods would get the same operation ids now and I fixed it. Also included in the tests.

**Review by tomasvanrijsse — APPROVED** [review]
